spring:
  application:
    name: demo-backend
  datasource:
    name: demo_mysql_db
    platform: mysql
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Toto4567
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000
